spring:
  application:
    name: category-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/category_db}

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 6000
      connect-timeout: 6000
  cache:
    type: redis

  elasticsearch:
    uris: ${ELASTIC_URI:http://localhost:9200}

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${SERVER_PORT:8090}

  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET:supersecretkeythatshouldbereplacedandstoredsecurely}

logging:
  level:
    root: INFO
    org.springframework.data.redis: WARN
    org.springframework.cache.interceptor: DEBUG


elastic:
  host:
    name: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: category-service

app:
  seed-categories: true

product:
  service:
    url: ${CATEGORY_SERVICE_URL:http://localhost:8080/api/v1/product}
