version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: shopfast-mongo
    environment:
      - MONGO_INITDB_DATABASE=shopfast
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    mem_limit: 2g
    ports:
      - 9200:9200


  redis:
    image: redis:7
    ports:
      - 6379:6379


  app:
    build: .
    container_name: product-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - mongo
      - elasticsearch
      - redis
    ports:
      - 8080:8080

volumes:
  mongo_data: