#!/usr/bin/env bash
#
# Backs up the Keycloak database.
#
# Why this needs its own script rather than riding along with the application
# database dump: keycloak_db is the only place where user credentials, TOTP
# secrets, federated-identity links and offline refresh tokens live. If it is
# lost, every user is locked out permanently - there is no other copy. The
# application databases only hold profile rows keyed by Keycloak's user id, and
# those ids are generated by Keycloak, so a restored-from-scratch realm does not
# line up with existing orders, carts or reviews.
#
# Restore is therefore a two-part guarantee: the realm *configuration* is in
# version control (keycloak/realm-export.json) and can be re-imported at any
# time, but the realm *data* (users and credentials) only exists in these dumps.
#
# Usage:
#   ./backup-keycloak-db.sh                 # write a timestamped dump
#   ./backup-keycloak-db.sh --verify FILE   # check a dump is restorable
#   RETENTION_DAYS=30 ./backup-keycloak-db.sh
#
set -euo pipefail

POSTGRES_CONTAINER="${POSTGRES_CONTAINER:-postgres}"
POSTGRES_USER="${POSTGRES_USER:-postgres}"
KEYCLOAK_DB="${KEYCLOAK_DB:-keycloak_db}"
BACKUP_DIR="${BACKUP_DIR:-./backups/keycloak}"
RETENTION_DAYS="${RETENTION_DAYS:-14}"

log() { printf '[%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }
die() { log "ERROR: $*" >&2; exit 1; }

# A dump that has never been test-restored is a hope, not a backup. This reads
# the custom-format archive's table of contents, which fails loudly if the file
# is truncated or corrupt, and checks that the tables that actually matter are
# present and were not dumped empty by a misconfigured connection.
verify_dump() {
  local file="$1"
  [[ -f "$file" ]] || die "no such dump: $file"

  log "Verifying $file"
  local toc
  toc="$(pg_restore --list "$file" 2>/dev/null)" \
    || die "pg_restore could not read $file - the archive is corrupt or truncated"

  for table in user_entity credential realm; do
    grep -q "TABLE DATA public $table" <<<"$toc" \
      || die "dump is missing table data for '$table' - it would restore an empty realm"
  done

  log "OK: archive is readable and contains user_entity, credential and realm data"
}

if [[ "${1:-}" == "--verify" ]]; then
  verify_dump "${2:?--verify requires a path to a dump file}"
  exit 0
fi

command -v docker >/dev/null || die "docker not found on PATH"
docker inspect "$POSTGRES_CONTAINER" >/dev/null 2>&1 \
  || die "container '$POSTGRES_CONTAINER' is not running"

mkdir -p "$BACKUP_DIR"
timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
target="${BACKUP_DIR}/keycloak_db-${timestamp}.dump"

# Custom format (-Fc) rather than plain SQL: it is compressed, and pg_restore can
# list and selectively restore from it, which is what makes verification possible.
log "Dumping ${KEYCLOAK_DB} from container ${POSTGRES_CONTAINER}"
if ! docker exec "$POSTGRES_CONTAINER" \
      pg_dump -U "$POSTGRES_USER" -d "$KEYCLOAK_DB" -Fc --no-owner > "$target"; then
  rm -f "$target"
  die "pg_dump failed - no backup was written"
fi

# Write the checksum next to the dump so a later restore can prove the file did
# not rot on disk or get truncated in transit to off-site storage.
sha256sum "$target" > "${target}.sha256"

size="$(du -h "$target" | cut -f1)"
log "Wrote ${target} (${size})"

if command -v pg_restore >/dev/null; then
  verify_dump "$target"
else
  log "WARN: pg_restore not installed locally - skipping verification."
  log "      Run '$0 --verify $target' from a host that has postgresql-client."
fi

# Retention is applied only after a successful, verified dump. Pruning before the
# new backup exists would risk deleting the last good copy when pg_dump fails.
log "Pruning dumps older than ${RETENTION_DAYS} days"
find "$BACKUP_DIR" -name 'keycloak_db-*.dump*' -type f -mtime "+${RETENTION_DAYS}" -print -delete || true

cat <<EOF

Restore procedure (destructive - the realm is replaced wholesale):

  docker exec -i ${POSTGRES_CONTAINER} psql -U ${POSTGRES_USER} -c \\
    "DROP DATABASE IF EXISTS ${KEYCLOAK_DB};"
  docker exec -i ${POSTGRES_CONTAINER} psql -U ${POSTGRES_USER} -c \\
    "CREATE DATABASE ${KEYCLOAK_DB};"
  docker exec -i ${POSTGRES_CONTAINER} pg_restore -U ${POSTGRES_USER} \\
    -d ${KEYCLOAK_DB} --no-owner < ${target}
  docker compose restart keycloak

Stop Keycloak before restoring. It caches realm state in memory and will write
stale rows back over the restored data if it is left running.
EOF
