apiVersion: v1
kind: Service
metadata:
  name: mail-imap
  namespace: shopfast
spec:
  selector:
    app: mail-server
  ports:
    - name: imap
      port: 143
      targetPort: 143
    - name: auth-tcp
      port: 2525
      targetPort: 2525
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mail-smtp
  namespace: shopfast
spec:
  selector:
    app: mail-server
  ports:
    - name: smtp
      port: 25
      targetPort: 25
    - name: submission
      port: 587
      targetPort: 587
    - name: submissions
      port: 465
      targetPort: 465
  type: ClusterIP
