apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-server
  namespace: shopfast
  labels:
    app: mail-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-server
  template:
    metadata:
      labels:
        app: mail-server
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      volumes:
        - name: mail-storage
          persistentVolumeClaim:
            claimName: mail-storage
        - name: postfix-tls
          emptyDir: {}
      containers:
        - name: dovecot
          image: localhost:5000/shopfast/dovecot:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 143
              name: imap
            - containerPort: 2525
              name: auth-tcp
          volumeMounts:
            - name: mail-storage
              mountPath: /var/mail
          readinessProbe:
            tcpSocket:
              port: 143
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
        - name: postfix
          image: localhost:5000/shopfast/postfix:v7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 25
              name: smtp
            - containerPort: 587
              name: submission
            - containerPort: 465
              name: submissions
          volumeMounts:
            - name: mail-storage
              mountPath: /var/mail
            - name: postfix-tls
              mountPath: /opt/postfix-tls
          readinessProbe:
            tcpSocket:
              port: 587
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
